# Generated by Django 5.2.8 on 2025-12-06 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='acercade',
            options={'verbose_name': 'Acerca de', 'verbose_name_plural': 'Acerca de'},
        ),
        migrations.AlterModelOptions(
            name='articulo',
            options={'ordering': ['-fecha_creacion'], 'verbose_name_plural': 'Artículos'},
        ),
        migrations.AlterModelOptions(
            name='categoria',
            options={'ordering': ['nombre'], 'verbose_name_plural': 'Categorías'},
        ),
        migrations.AlterModelOptions(
            name='comentario',
            options={'ordering': ['fecha_creacion'], 'verbose_name_plural': 'Comentarios'},
        ),
        migrations.AlterModelOptions(
            name='mensajecontacto',
            options={'ordering': ['-fecha_creacion'], 'verbose_name_plural': 'Mensajes de Contacto'},
        ),
        migrations.AlterModelOptions(
            name='perfil',
            options={'verbose_name_plural': 'Perfiles'},
        ),
    ]
