# Generated by Django 6.0 on 2025-12-12 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_acercade_options_alter_articulo_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='rol',
            field=models.CharField(choices=[('miembro', 'Miembro'), ('colaborador', 'Colaborador'), ('administrador', 'Administrador')], default='miembro', max_length=20),
        ),
    ]
